name: Unit Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        make_target: [test, vet]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code repository source code
        uses: actions/checkout@v2.3.5

      - uses: actions/cache@v2.1.5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions
      - name: Set build variables
        run: |
          echo "::set-env name=MAKE_TARGET::${{ matrix.make_target }}"
      - name: Run ${{matrix.make_target}}
        run: |
          make $MAKE_TARGET
